
name: deployment

on:
  push:
      branches: ["main"]

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: pages-deployment
        uses: actions/deploy-pages@v4
