
name: deployment

on:
  push:
      branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: pages-deployment
        uses: actions/deploy-pages@v4
